defaults :
  - physicsnemo_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.95
  decay_steps: 4000

training:
 rec_validation_freq: 500
 rec_inference_freq: 1000
 rec_monitor_freq: 200
 rec_constraint_freq: 5000
 max_steps: 5000

batch_size:
 bc_min: 200
 bc_max: 10
 interior: 2000


graph:
 func_arch: true
