defaults :
  - physicsnemo_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.9
  decay_steps: 2000

training:
 rec_validation_freq: 500
 rec_inference_freq: 1000
 rec_monitor_freq: 200
 rec_constraint_freq: 5000
 max_steps: 20000

batch_size:
 bc_min: 200
 bc_max: 200
 interior: 2000

optimizer_lbfgs:
  name: lbfgs
  max_iter: 500
  tolerance_grad: 1e-6
  history_size: 100
  line_search_fn: strong_wolfe

graph:
 func_arch: true
