defaults :
  - physicsnemo_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.9
  decay_steps: 2000

training:
 rec_validation_freq: 500
 rec_monitor_freq: 1000
 rec_constraint_freq: 1000
 max_steps: 5000

batch_size:
 bc_min: 200
 bc_max: 200
 interior: 500

graph:
 func_arch: true

hparams:
  lr: 1e-3
  batch_size_train: 1024
  metric_path: val_metric.json
  width: 64
  depth: 4
  activation: "tanh"
